/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LImage: typeof import('./src/components/LImage/LImage.vue')['default']
    LShape: typeof import('./src/components/LShape/LShape.vue')['default']
    LText: typeof import('./src/components/LText/LText.vue')['default']
  }
}
